### ISSUE TITLE
Failed to run the DCGM Exporter with specific mig profile.

### ISSUE THREAD

**Issue by Kaka1127** [NVIDIA/gpu-operator#276]
_The template below is mostly useful for bug reports and support questions. Feel free to remove anything which doesn't apply to you and add more information where it makes sense._

### 1. Quick Debug Checklist
- [ ] Are you running on an Ubuntu 18.04 node? --> No, ubuntu 20.04
- [x] Are you running Kubernetes v1.13+?
- [x] Are you running Docker (>= 18.06) or CRIO (>= 1.13+)?
- [x] Do you have `i2c_core` and `ipmi_msghandler` loaded on the nodes?
- [x] Did you apply the CRD (`kubectl describe clusterpolicies --all-namespaces`)

### 1. Issue or feature description

When set the custom mig profile for A100 40GB PCIe card by mig manager, it failed to run the DCGM Exporter.

### 2. Steps to reproduce the issue

1. Deployed the pre released v1.8.2 operator.
2. Add the custom profile
```
  a100-server-b-20211026:
  - devices:
    - 0
    mig-devices:
      3g.20gb: 2
    mig-enabled: true
  - devices:
    - 1
    mig-devices:
      1g.5gb: 7
    mig-enabled: true
```
3. Changed the label for instance.

Here is the log file on dcgm-exporter when set this profile.

```
time="2021-10-29T07:17:07Z" level=info msg="Starting dcgm-exporter" 
time="2021-10-29T07:17:07Z" level=info msg="Attemping to connect to remote hostengine at 211.14.19.111:5555" 
time="2021-10-29T07:17:07Z" level=info msg="DCGM successfully initialized!" 
time="2021-10-29T07:17:07Z" level=info msg="Collecting DCP Metrics" 
panic: runtime error: index out of range [2] with length 2 
 
goroutine 1 [running]: 
main.InitializeSystemInfo(0x1, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
	/go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/system_info.go:196 +0x920 
main.NewDCGMCollector(0xc0002f2000, 0x17, 0x41, 0xc0002fac00, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...) 
	/go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/gpu_collector.go:26 +0x80 
main.NewMetricsPipeline(0xc00028d040, 0xa, 0xc000150ea0, 0x1, 0x1) 
	/go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/pipeline.go:42 +0x17e 
main.Run(0xc00014f600, 0x0, 0x0) 
	/go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/main.go:173 +0x3e0 
main.main.func1(0xc00014f600, 0xc00000fb00, 0x12) 
	/go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/main.go:128 +0x2b 
github.com/urfave/cli/v2.(*App).RunContext(0xc00016ba00, 0xc1c740, 0xc00002c050, 0xc0000201d0, 0x1, 0x1, 0x0, 0x0) 
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:322 +0x70b 
github.com/urfave/cli/v2.(*App).Run(...) 
	/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224 
main.main() 
	/go/src/github.com/NVIDIA/gpu-monitoring-tools/pkg/main.go:131 +0xcaf 
```
### 3. Information to [attach](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/) (optional if deemed irrelevant)

 - [x] kubernetes pods status: `kubectl get pods --all-namespaces`
```
NAMESPACE                NAME                                                          READY   STATUS      RESTARTS   AGE
cattle-system            cattle-cluster-agent-6d969d75b8-x6s8w                         1/1     Running     8          116d
cattle-system            cattle-node-agent-zbxjz                                       1/1     Running     8          116d
default                  gpu-operator-68c95b5679-6298n                                 1/1     Running     11         52d
default                  gpu-operator-node-feature-discovery-master-58d884d5cc-2r8dm   1/1     Running     1          74d
default                  gpu-operator-node-feature-discovery-worker-6zmd8              1/1     Running     5          74d
gpu-operator-resources   gpu-feature-discovery-9nktj                                   1/1     Running     0          69s
gpu-operator-resources   nvidia-container-toolkit-daemonset-6qf8q                      1/1     Running     1          37d
gpu-operator-resources   nvidia-cuda-validator-whd5c                                   0/1     Completed   0          29s
gpu-operator-resources   nvidia-dcgm-67zpl                                             1/1     Running     0          69s
gpu-operator-resources   nvidia-dcgm-exporter-klcd4                                    0/1     Error       2          69s
gpu-operator-resources   nvidia-device-plugin-daemonset-jp2s4                          1/1     Running     0          69s
gpu-operator-resources   nvidia-device-plugin-validator-rbsl4                          0/1     Completed   0          8s
gpu-operator-resources   nvidia-driver-daemonset-8swtd                                 1/1     Running     1          52d
gpu-operator-resources   nvidia-mig-manager-bxwj8                                      1/1     Running     1          37d
gpu-operator-resources   nvidia-operator-validator-q8jdq                               1/1     Running     0          32s
kube-system              calico-kube-controllers-6949477b58-jsprr                      1/1     Running     8          116d
kube-system              calico-node-p8b2p                                             1/1     Running     8          116d
kube-system              coredns-74ff55c5b-288sr                                       1/1     Running     8          116d
kube-system              coredns-74ff55c5b-nm7vm                                       1/1     Running     8          116d
kube-system              etcd-a100-server-b                                            1/1     Running     8          116d
kube-system              kube-apiserver-a100-server-b                                  1/1     Running     10         116d
kube-system              kube-controller-manager-a100-server-b                         1/1     Running     10         116d
kube-system              kube-proxy-jkdm4                                              1/1     Running     8          116d
kube-system              kube-scheduler-a100-server-b                                  1/1     Running     10         116d
monitoring               kube-prometheus-stack-grafana-5c5c84b568-4r96r                2/2     Running     14         115d
monitoring               kube-prometheus-stack-kube-state-metrics-6f85498dd8-xsdzs     1/1     Running     7          115d
monitoring               kube-prometheus-stack-operator-64c65d9fdd-9z7mn               1/1     Running     7          115d
monitoring               kube-prometheus-stack-prometheus-node-exporter-lvlkw          1/1     Running     13         115d
monitoring               prometheus-kube-prometheus-stack-prometheus-0                 2/2     Running     15         115d
```
 - [x] kubernetes daemonset status: `kubectl get ds --all-namespaces`
```
NAMESPACE                NAME                                             DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                      AGE
cattle-system            cattle-node-agent                                1         1         1       1            1           <none>                                             116d
default                  gpu-operator-node-feature-discovery-worker       1         1         1       1            1           <none>                                             74d
gpu-operator-resources   gpu-feature-discovery                            1         1         1       1            1           nvidia.com/gpu.deploy.gpu-feature-discovery=true   74d
gpu-operator-resources   nvidia-container-toolkit-daemonset               1         1         1       1            1           nvidia.com/gpu.deploy.container-toolkit=true       74d
gpu-operator-resources   nvidia-dcgm                                      1         1         1       1            1           nvidia.com/gpu.deploy.dcgm=true                    74d
gpu-operator-resources   nvidia-dcgm-exporter                             1         1         0       1            0           nvidia.com/gpu.deploy.dcgm-exporter=true           74d
gpu-operator-resources   nvidia-device-plugin-daemonset                   1         1         1       1            1           nvidia.com/gpu.deploy.device-plugin=true           74d
gpu-operator-resources   nvidia-driver-daemonset                          1         1         1       1            1           nvidia.com/gpu.deploy.driver=true                  74d
gpu-operator-resources   nvidia-mig-manager                               1         1         1       1            1           nvidia.com/gpu.deploy.mig-manager=true             74d
gpu-operator-resources   nvidia-operator-validator                        1         1         1       1            1           nvidia.com/gpu.deploy.operator-validator=true      74d
kube-system              calico-node                                      1         1         1       1            1           kubernetes.io/os=linux                             116d
kube-system              kube-proxy                                       1         1         1       1            1           kubernetes.io/os=linux                             116d
monitoring               kube-prometheus-stack-prometheus-node-exporter   1         1         1       1            1           <none>                                             115d
```
 - [x] Docker configuration file: `cat /etc/docker/daemon.json`
```
{
    "default-runtime": "nvidia",
    "exec-opts": [
        "native.cgroupdriver=systemd"
    ],
    "runtimes": {
        "nvidia": {
            "args": [],
            "path": "/usr/local/nvidia/toolkit/nvidia-container-runtime"
        },
        "nvidia-experimental": {
            "args": [],
            "path": "/usr/local/nvidia/toolkit/nvidia-container-runtime-experimental"
        }
    },
    "storage-driver": "overlay2",
    "storage-opts": [
        "overlay2.override_kernel_check=true"
    ]
}
```
 - [x] Docker runtime configuration: `docker info | grep Runtime`
```
 Runtimes: nvidia nvidia-experimental runc
WARNING: No swap limit support
 Default Runtime: nvidia
```
 - [x] NVIDIA shared directory: `ls -la /run/nvidia`
```
total 12
drwxr-xr-x  4 root root  120 Sep 21 23:10 .
drwxr-xr-x 40 root root 1340 Oct 29 07:36 ..
drwxr-xr-x  1 root root 4096 Sep 21 23:09 driver
-rw-r--r--  1 root root    6 Sep 21 23:09 nvidia-driver.pid
-rw-r--r--  1 root root    6 Sep 21 23:10 toolkit.pid
drwxr-xr-x  2 root root  120 Oct 29 07:38 validations
```
 - [x] NVIDIA packages directory: `ls -la /usr/local/nvidia/toolkit`
```
total 8552
drwxr-xr-x 3 root root    4096 Sep 21 23:10 .
drwxr-xr-x 3 root root    4096 Sep 21 23:10 ..
drwxr-xr-x 3 root root    4096 Sep 21 23:10 .config
lrwxrwxrwx 1 root root      28 Sep 21 23:10 libnvidia-container.so.1 -> libnvidia-container.so.1.4.0
-rwxr-xr-x 1 root root  175120 Sep 21 23:10 libnvidia-container.so.1.4.0
-rwxr-xr-x 1 root root     154 Sep 21 23:10 nvidia-container-cli
-rwxr-xr-x 1 root root   43024 Sep 21 23:10 nvidia-container-cli.real
-rwxr-xr-x 1 root root     342 Sep 21 23:10 nvidia-container-runtime
-rwxr-xr-x 1 root root     429 Sep 21 23:10 nvidia-container-runtime-experimental
-rwxr-xr-x 1 root root 3991000 Sep 21 23:10 nvidia-container-runtime.experimental
lrwxrwxrwx 1 root root      24 Sep 21 23:10 nvidia-container-runtime-hook -> nvidia-container-toolkit
-rwxr-xr-x 1 root root 2359384 Sep 21 23:10 nvidia-container-runtime.real
-rwxr-xr-x 1 root root     198 Sep 21 23:10 nvidia-container-toolkit
-rwxr-xr-x 1 root root 2147896 Sep 21 23:10 nvidia-container-toolkit.real
```
 - [x] NVIDIA driver directory: `ls -la /run/nvidia/driver`
```
total 88
drwxr-xr-x    1 root root  4096 Sep 21 23:09 .
drwxr-xr-x    4 root root   120 Sep 21 23:10 ..
lrwxrwxrwx    1 root root     7 Jul 23 17:35 bin -> usr/bin
drwxr-xr-x    2 root root  4096 Apr 15  2020 boot
drwxr-xr-x   17 root root  4340 Sep 21 23:10 dev
-rwxr-xr-x    1 root root     0 Sep 21 23:09 .dockerenv
drwxr-xr-x    1 root root  4096 Sep 21 23:09 drivers
drwxr-xr-x    1 root root  4096 Sep 21 23:10 etc
drwxr-xr-x    2 root root  4096 Apr 15  2020 home
drwxr-xr-x    2 root root  4096 Sep 21 23:09 host-etc
lrwxrwxrwx    1 root root     7 Jul 23 17:35 lib -> usr/lib
lrwxrwxrwx    1 root root     9 Jul 23 17:35 lib32 -> usr/lib32
lrwxrwxrwx    1 root root     9 Jul 23 17:35 lib64 -> usr/lib64
lrwxrwxrwx    1 root root    10 Jul 23 17:35 libx32 -> usr/libx32
drwxr-xr-x    2 root root  4096 Jul 23 17:35 media
drwxr-xr-x    2 root root  4096 Jul 23 17:35 mnt
-rw-r--r--    1 root root 16047 Aug  3 20:33 NGC-DL-CONTAINER-LICENSE
drwxr-xr-x    2 root root  4096 Jul 23 17:35 opt
dr-xr-xr-x 1290 root root     0 Sep 21 23:03 proc
drwx------    2 root root  4096 Jul 23 17:38 root
drwxr-xr-x    1 root root  4096 Sep 21 23:10 run
lrwxrwxrwx    1 root root     8 Jul 23 17:35 sbin -> usr/sbin
drwxr-xr-x    2 root root  4096 Jul 23 17:35 srv
dr-xr-xr-x   13 root root     0 Sep 21 23:09 sys
drwxrwxrwt    1 root root  4096 Sep 21 23:10 tmp
drwxr-xr-x    1 root root  4096 Jul 23 17:35 usr
drwxr-xr-x    1 root root  4096 Jul 23 17:38 var
```
 - [ ] kubelet logs `journalctl -u kubelet > kubelet.logs`
If you need, please let me know.

**Comment by shivamerla** [comment]
@Kaka1127 Can you try with new DCGM exporter version `nvcr.io/nvidia/k8s/dcgm-exporter:2.3.1-2.6.0-ubuntu20.04` and verify this.

**Comment by Kaka1127** [comment]
@shivamerla 
Thank you for your response!
I have changed the the DCGM exporter tag and it was worked well by updated the DCGM. So, please update the tag of DCGM exporter in next GPU Operator version.
